# **Logistic Regression**

In [65]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import numpy as np

from sklearn.feature_selection import RFE, RFECV

from matplotlib.colors import ListedColormap 

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, log_loss, brier_score_loss, confusion_matrix
from sklearn.decomposition import PCA

# Display all columns and rows of the dataset
pd.options.display.max_columns = None
pd.options.display.max_rows = None
warnings.filterwarnings("ignore")

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [54]:
# Load dataset
df = pd.read_csv("/content/gdrive/MyDrive/Thesis/MODELING/Encoded.csv")

In [55]:
# Size of dataset
df.shape

(28990, 291)

In [56]:
df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'], inplace=True)
df.head()

tourney_id  location  draw_size  series  money_prize  year  month  day  \
0         339       1.0         32     0.0       372500  2010      1    3   
1         339       1.0         32     0.0       372500  2010      1    3   
2         339       1.0         32     0.0       372500  2010      1    3   
3         339       1.0         32     0.0       372500  2010      1    3   
4         339       1.0         32     0.0       372500  2010      1    3   

   match_num  best_of  round    A_id    B_id  A_rank  B_rank  A_hand   A_ht  \
0          1        3    0.0  104053  103429     7.0    77.0     1.0  188.0   
1          2        3    0.0  104999  104958    78.0   134.0     0.0  190.0   
2          3        3    0.0  103813  104755    88.0    52.0     0.0  185.0   
3          4        3    0.0  103781  105051    28.0   285.0     0.0  183.0   
4          5        3    0.0  105194  104607   251.0    20.0     1.0  183.0   

       A_age  B_hand   B_ht      B_age  A_rank_points  B_rank_points  A_B365  \
0  27.348392     1.0  183.0  30.346338         4410.0          598.0    1.08   
1  22.370979     0.0  198.0  22.543463          590.0          400.0    1.66   
2  28.451745     1.0  185.0  23.548255          568.0          850.0    2.62   
3  28.621492     1.0  188.0  22.108145         1260.0          151.0    1.14   
4  21.429158     1.0  196.0  24.298426          179.0         1655.0    5.50   

   B_B365  Label  home_advantage  A_rank_log  B_rank_log  A_rank_points_log  \
0    7.00      1              -1    2.807355    6.266787          12.106563   
1    2.10      0               1    6.285402    7.066089           9.204571   
2    1.44      0               0    6.459432    5.700440           9.149747   
3    5.00      0               1    4.807355    8.154818          10.299208   
4    1.12      0              -1    7.971544    4.321928           7.483816   

   B_rank_points_log  match_quality1  match_quality2  surface_court  \
0           9.224002            84.0        9.074141            4.0   
1           8.643856           212.0       13.351491            4.0   
2           9.731319           140.0       12.159871            4.0   
3           7.238405           313.0       12.962173            4.0   
4          10.692616           271.0       12.293472            4.0   

   B365_ratio   A_spread   B_spread  A_wins_career  A_losses_career  \
0    0.154286   8.193092  71.613969            0.0              0.0   
1    1.265060  71.613969   8.193092            0.0              0.0   
2    0.549618  71.613969   8.193092            0.0              0.0   
3    4.385965  71.613969   8.193092            0.0              0.0   
4    0.203636  71.613969   8.193092            0.0              0.0   

   A_matches_career  A_titles_career  B_wins_career  B_losses_career  \
0               0.0              0.0            0.0              0.0   
1               0.0              0.0            0.0              0.0   
2               0.0              0.0            0.0              0.0   
3               0.0              0.0            0.0              0.0   
4               0.0              0.0            0.0              0.0   

   B_matches_career  B_titles_career  A_wins_year  A_losses_year  \
0               0.0              0.0          0.0            0.0   
1               0.0              0.0          0.0            0.0   
2               0.0              0.0          0.0            0.0   
3               0.0              0.0          0.0            0.0   
4               0.0              0.0          0.0            0.0   

   A_matches_year  A_titles_year  B_wins_year  B_losses_year  B_matches_year  \
0             0.0            0.0          0.0            0.0             0.0   
1             0.0            0.0          0.0            0.0             0.0   
2             0.0            0.0          0.0            0.0             0.0   
3             0.0            0.0          0.0            0.0             0.0   
4            

In [57]:
# keep only differences
df.drop(columns=['A_rank', 'B_rank', 'A_hand', 'B_hand', 'A_ht', 'B_ht', 'A_age', 'B_age', 'A_rank_points', 'B_rank_points', 'A_B365', 'B_B365', 'A_rank_log', 'B_rank_log',
                 'A_rank_points_log', 'B_rank_points_log', 'A_spread', 'B_spread', 'A_wins_career', 'A_losses_career', 'A_matches_career', 'A_titles_career', 'B_wins_career', 'B_losses_career',
                 'B_matches_career', 'B_titles_career', 'A_wins_year', 'A_losses_year', 'A_matches_year', 'A_titles_year', 'B_wins_year', 'B_losses_year', 'B_matches_year', 'B_titles_year', 
                 'A_matches_year_per', 'B_matches_year_per', 'A_wins_semester', 'A_losses_semester',  'A_matches_semester', 'A_titles_semester', 'B_wins_semester', 'B_losses_semester',
                 'B_matches_semester', 'B_titles_semester', 'A_wins_recent', 'A_losses_recent', 'A_matches_recent', 'A_titles_recent', 'B_wins_recent', 'B_losses_recent', 'B_matches_recent', 'B_titles_recent', 
                 'A_matches_per_surface', 'A_wins_per_surface', 'A_losses_per_surface', 'A_titles_per_surface', 'B_matches_per_surface', 'B_wins_per_surface', 'B_losses_per_surface', 'B_titles_per_surface',
                 'A_surface_per', 'B_surface_per', 'A_wins_tour', 'A_losses_tour', 'A_matches_tour', 'A_titles_tour', 'B_wins_tour', 'B_losses_tour', 'B_matches_tour', 'B_titles_tour', 'A_tour_per', 'B_tour_per',
                 'A_round_wins', 'A_round_losses', 'A_round_matches', 'A_round_per', 'B_round_wins', 'B_round_losses', 'B_round_matches', 'B_round_per', 'A_elo_rating', 'B_elo_rating', 'A_ratio_ace/df_year', 'B_ratio_ace/df_year',
                 'A_ace_career', 'A_df_career', 'A_svpt_career', 'A_1stIn_career', 'A_1stWon_career', 'A_2ndWon_career', 'A_SvGms_career', 'A_bpSaved_career', 'A_bpFaced_career', 'A_2ndIn_career', 'A_1stSvrptWon_career', 
                 'A_2ndSvrptWon_career', 'A_1stServeWon_career', 'A_2ndServeWon_career', 'A_1stServe_career', 'A_bpSavedratio_career', 'A_bpWon_career', 'A_bpConv_career', 'B_ace_career', 'B_df_career',
                 'B_svpt_career', 'B_1stIn_career', 'B_1stWon_career', 'B_2ndWon_career', 'B_SvGms_career', 'B_bpSaved_career', 'B_bpFaced_career', 'B_2ndIn_career', 'B_1stSvrptWon_career', 'B_2ndSvrptWon_career',
                 'B_1stServeWon_career', 'B_2ndServeWon_career', 'B_1stServe_career', 'B_bpSavedratio_career', 'B_bpWon_career', 'B_bpConv_career', 'A_ace_year', 'A_df_year', 'A_svpt_year', 'A_1stIn_year', 'A_1stWon_year',
                 'A_2ndWon_year', 'A_SvGms_year', 'A_bpSaved_year', 'A_bpFaced_year', 'A_bpWon_year', 'A_bpConv_year', 'A_2ndIn_year', 'A_1stSvrptWon_year', 'A_2ndSvrptWon_year', 'A_1stServeWon_year', 'A_2ndServeWon_year',
                 'A_1stServe_year', 'A_bpSavedratio_year', 'B_ace_year', 'B_df_year', 'B_svpt_year', 'B_1stIn_year', 'B_1stWon_year', 'B_2ndWon_year', 'B_SvGms_year', 'B_bpSaved_year', 'B_bpFaced_year', 'B_bpWon_year',
                 'B_bpConv_year', 'B_2ndIn_year', 'B_1stSvrptWon_year', 'B_2ndSvrptWon_year', 'B_1stServeWon_year', 'B_2ndServeWon_year', 'B_1stServe_year', 'B_bpSavedratio_year', 'A_over_B', 'B_over_A', 'A_Win_oppon', 
                 'B_Win_oppon', 'A_wstreak', 'A_lstreak', 'A_days_inactive', 'B_wstreak', 'B_lstreak', 'B_days_inactive', 'A_momentum', 'B_momentum'], 
        inplace=True)

In [59]:
def training(MODEL, X, y, SCALER, PCAer, n=20):
  
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
  
  if SCALER == True:
    print('USING SCALING..')
    scaler = StandardScaler()
    #scaler = MinMaxScaler()  
    #scaler = MaxAbsScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
  
  if PCAer == True:
    print('USING PCA..')
    pca_tf = PCA(n_components=n)
    pca_tf.fit(X_train)
    X_train = pca_tf.transform(X_train)
    X_test = pca_tf.transform(X_test)

  model = MODEL
  start_time = datetime.datetime.now()
  model.fit(X_train, y_train)
  end_time = datetime.datetime.now()
  elapsed_time = end_time - start_time
  print('Training time:', str(elapsed_time))
  print()

  predict = model.predict(X_test)
  print("\nAccuracy               :", round(accuracy_score(y_test, predict) * 100, 3), '%.')
  print("Precision              :", round(precision_score(y_test, predict) * 100, 3), '%.')
  print("Recall Score           :", round(recall_score(y_test, predict) * 100, 3), '%.')
  print("F1 Score               :", round(f1_score(y_test, predict) * 100, 3), '%.')
  print("Log-Loss               :", round(log_loss(y_test, predict), 3), '.')
  print("Brier Score            :", round(brier_score_loss(y_test, predict) * 100, 3), '%.')
  print("Confusion Matrix")
  print(confusion_matrix(y_test, predict))

  print('\nTrain Score            :', round(model.score(X_train, y_train) * 100,3), '%.')
  print('Test Score             :', round(model.score(X_test, y_test) * 100, 3), '%.')

In [60]:
df.sample(10)

tourney_id  location  draw_size  series  money_prize  year  month  day  \
10899         403      39.0         96     3.0      4720380  2014      3   19   
15326         580       1.0        128     2.0     19703000  2016      1   18   
10392         580       1.0        128     2.0     14982200  2014      1   13   
15861         404      39.0        128     3.0      6134605  2016      3    7   
2172         1720      35.0         28     0.0       551000  2010      9   27   
3807          520      13.0        128     2.0      7884000  2011      5   22   
24431         315      38.0         32     0.0       583585  2019      7   15   
307           505       7.0         32     0.0       398250  2010      2    1   
23747        7648      15.0         32     0.0       524340  2019      4   22   
7738          301      25.0         28     0.0       433400  2013      1    7   

       match_num  best_of  round    A_id    B_id  Label  home_advantage  \
10899         64        3    1.0  104871  104925      0               0   
15326        103        5    0.0  104559  104312      0               0   
10392        105        5    2.0  104607  106000      1               0   
15861        315        3    4.0  105453  104745      0               0   
2172          12        3    0.0  104999  103794      0               0   
3807          75        5    1.0  104890  105238      0               0   
24431        284        3    0.0  111794  202400      1               0   
307           16        3    0.0  103454  104338      0              -1   
23747        288        3    1.0  105732  104897      1               0   
7738           8        3    0.0  104368  105028      0              -1   

       match_quality1  match_quality2  surface_court  B365_ratio  \
10899       50.000000        6.584963            4.0    0.060000   
15326       73.000000       10.317413            4.0    0.731818   
10392      195.000000       10.361944            4.0    0.053684   
15861       11.000000        4.906891            4.0    1.111111   
2172       180.000000       12.867858            3.0    0.697778   
3807       110.000000       10.918863            1.0    0.228000   
24431      190.130826       13.134000            2.0    0.157143   
307        127.000000       11.472691            1.0    0.305000   
23747      178.000000       12.625937            1.0    0.382353   
7738       480.000000       15.255029            4.0    0.186667   

       preferred_hand        rank  rank_points  rank_log  rank_points_log  \
10899             3.0   46.000000 -9945.000000  4.584963        -3.512684   
15326             3.0   15.000000  -357.000000  0.601451        -0.467422   
10392             3.0 -181.000000  3908.000000 -4.747234         3.941824   
15861             1.0    1.000000  -830.000000  0.263034        -0.273268   
2172              2.0   50.000000  -260.000000  0.823122        -0.627675   
3807              3.0   66.000000  -868.000000  2.000000        -1.316962   
24431             3.0   13.869174  -598.838888  0.210851        -1.062673   
307               3.0   69.000000  -713.000000  1.756729        -1.218934   
23747             3.0  -80.000000   529.000000 -1.396517         1.140786   
7738              1.0  272.000000  -423.000000  1.854149        -2.308382   

            age     height     spread   B365  wins_career  losses_career  \
10899  0.271047   0.000000  30.332091  15.98       -177.0           54.0   
15326 -1.300000  -2.000000   5.471125   0.59        -93.0          -64.0   
10392  6.672142  24.000000 -61.586636 -17.98        194.0           87.0   
15861 -3.600000  -7.000000   1.276840  -0.20       -151.0           17.0   
2172  -6.182067  12.000000   1.602417   0.68         -9.0          -11.0   
3807   1.631759  10.000000   9.502871   3.86        -34.0          -29.0   
24431  2.500000  -3.481884 -22.672008  -5.90          0.0            2.0   
307    4.468172  -2.000000  63.420876   2.78         -2.0           -2.0   
23747 -4

## Baseline Model

In [61]:
baseline = df[['rank', 'Label']]
          
eval_df = baseline.copy()

y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

baseline_model = LogisticRegression()
print('Model: ', str(baseline_model))
training(baseline_model, X, y, SCALER=False, PCAer=False)
print('\n################################\n')

Model:  LogisticRegression()
Training time: 0:00:00.044923


Accuracy               : 65.586 %.
Precision              : 65.129 %.
Recall Score           : 66.943 %.
F1 Score               : 66.023 %.
Log-Loss               : 11.886 .
Brier Score            : 34.414 %.
Confusion Matrix
[[2796 1557]
 [1436 2908]]

Train Score            : 65.895 %.
Test Score             : 65.586 %.

################################



## Feature Selection

### Recursive Feature Elimination

In [64]:
eval_df = df.copy()
y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=20)
rfe = rfe.fit(X, y)
print('Selected features: %s' % list(X.columns[rfe.support_]))

Selected features: ['round', 'rank_points_log', 'spread', 'B365', 'matches_year_per', 'wins_tour', 'losses_tour', 'SvGms_career', 'svpt_year', '1stWon_year', '2ndWon_year', 'bpFaced_year', 'headtohead', 'Win_oppon', 'wstreak', 'lstreak', 'svpt_common_op', '1stWon_common_op', 'bpSaved_common_op', 'bpWon_common_op']


In [71]:
opt_ft1 = df[['round', 'rank_points_log', 'spread', 'B365', 'matches_year_per', 'wins_tour', 'losses_tour',
             'SvGms_career', 'svpt_year', '1stWon_year', '2ndWon_year', 'bpFaced_year', 'headtohead',
             'Win_oppon', 'wstreak', 'lstreak', 'svpt_common_op', '1stWon_common_op',
             'bpSaved_common_op', 'bpWon_common_op',
             'Label']]

eval_df = opt_ft1.copy()

y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

baseline_model = LogisticRegression()

print('Model: ', str(baseline_model))
training(baseline_model, X, y, SCALER=False, PCAer=False)
print('\n################################\n')

Model:  LogisticRegression()
Training time: 0:00:00.273382


Accuracy               : 75.451 %.
Precision              : 75.142 %.
Recall Score           : 75.99 %.
F1 Score               : 75.564 %.
Log-Loss               : 8.479 .
Brier Score            : 24.549 %.
Confusion Matrix
[[3261 1092]
 [1043 3301]]

Train Score            : 75.75 %.
Test Score             : 75.451 %.

################################



### Feature ranking with recursive feature elimination and cross-validation

In [67]:
eval_df = df.copy()
y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

rfecv = RFECV(estimator=LogisticRegression(), step=1, cv=5, scoring='accuracy')
rfecv.fit(X, y)

print("Optimal number of features: %d" % rfecv.n_features_)
print('Selected features: %s' % list(X.columns[rfecv.support_]))

Optimal number of features: 30
Selected features: ['round', 'rank_points_log', 'spread', 'B365', 'wins_career', 'matches_year_per', 'wins_tour', 'losses_tour', 'titles_tour', 'elo_rating', 'SvGms_career', '2ndIn_career', 'ace_year', 'df_year', 'svpt_year', '1stWon_year', '2ndWon_year', 'bpSaved_year', 'bpFaced_year', 'headtohead', 'Win_oppon', 'wstreak', 'lstreak', 'ace_common_op', 'svpt_common_op', '1stWon_common_op', 'SvGms_common_op', 'bpSaved_common_op', 'bpWon_common_op', '2ndSvrptWon_common_op']


In [72]:
opt_ft2 = df[['round', 'rank_points_log', 'spread', 'B365', 'wins_career', 'matches_year_per', 'wins_tour',
             'losses_tour', 'titles_tour', 'elo_rating', 'SvGms_career', '2ndIn_career', 'ace_year', 'df_year',
             'svpt_year', '1stWon_year', '2ndWon_year', 'bpSaved_year', 'bpFaced_year', 'headtohead', 'Win_oppon',
             'wstreak', 'lstreak', 'ace_common_op', 'svpt_common_op', '1stWon_common_op', 'SvGms_common_op',
             'bpSaved_common_op', 'bpWon_common_op', '2ndSvrptWon_common_op',
             'Label']]

eval_df = opt_ft2.copy()

y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

baseline_model = LogisticRegression()

print('Model: ', str(baseline_model))
training(baseline_model, X, y, SCALER=False, PCAer=False)
print('\n################################\n')

Model:  LogisticRegression()
Training time: 0:00:00.290429


Accuracy               : 77.877 %.
Precision              : 76.961 %.
Recall Score           : 79.512 %.
F1 Score               : 78.216 %.
Log-Loss               : 7.641 .
Brier Score            : 22.123 %.
Confusion Matrix
[[3319 1034]
 [ 890 3454]]

Train Score            : 77.574 %.
Test Score             : 77.877 %.

################################



### Manually Feature Selection

In [74]:
opt_ft3 = df[['elo_rating', 'Win_oppon', 'wins_career', 'rank_points',
          'matches_career', 'headtohead', 'spread', 'momentum',
          'losses_per_surface', 'home_advantage',
          'Label']]

eval_df = opt_ft3.copy()

y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

baseline_model = LogisticRegression()

print('Model: ', str(baseline_model))
training(baseline_model, X, y, SCALER=False, PCAer=False)
print('\n################################\n')

Model:  LogisticRegression()
Training time: 0:00:00.280256


Accuracy               : 78.636 %.
Precision              : 77.5 %.
Recall Score           : 80.64 %.
F1 Score               : 79.039 %.
Log-Loss               : 7.379 .
Brier Score            : 21.364 %.
Confusion Matrix
[[3336 1017]
 [ 841 3503]]

Train Score            : 78.342 %.
Test Score             : 78.636 %.

################################



## Hyperparameter Tuning

#### Scaling

In [75]:
eval_df = opt_ft3.copy()

y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

baseline_model = LogisticRegression()
print('Model: ', str(baseline_model))
training(baseline_model, X, y, SCALER=True, PCAer=False)
print('\n################################\n')

Model:  LogisticRegression()
USING SCALING..
Training time: 0:00:00.059557


Accuracy               : 78.579 %.
Precision              : 78.085 %.
Recall Score           : 79.397 %.
F1 Score               : 78.735 %.
Log-Loss               : 7.399 .
Brier Score            : 21.421 %.
Confusion Matrix
[[3385  968]
 [ 895 3449]]

Train Score            : 78.273 %.
Test Score             : 78.579 %.

################################



#### Hyperparameters

In [85]:
eval_df = opt_ft3.copy()

y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

param_grid = {'solver': ['lbfgs', 'newton-cg', 'newton-cholesky', 'sag'],
              'penalty': ['l2', None],
              'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              'max_iter': [100, 250]}

model = LogisticRegression()
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X, y)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.783558 using {'C': 10, 'max_iter': 250, 'penalty': 'l2', 'solver': 'lbfgs'}


In [83]:
eval_df = opt_ft3.copy()
y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

param_grid = {'solver': ['liblinear'],
              'penalty': ['l1', 'l2'],
              'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              'max_iter': [100, 250, 500]}

model = LogisticRegression()
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X, y)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.783339 using {'C': 100, 'max_iter': 100, 'penalty': 'l1', 'solver': 'liblinear'}


In [84]:
eval_df = opt_ft3.copy()
y = eval_df['Label']
eval_df.drop(columns=['Label'], inplace=True)
X = eval_df

param_grid = {'solver': ['saga'],
              'penalty': ['l1', 'l2', 'elasticnet', None],
              'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
              'max_iter': [100, 250, 500]}

model = LogisticRegression()
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X, y)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.763367 using {'C': 0.001, 'max_iter': 500, 'penalty': 'l1', 'solver': 'saga'}
